/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Forms.Controllers.AssignedMeetingsController;
import Models.Meeting;
import Models.Report;
import java.text.SimpleDateFormat;

/**
 *
 * @author Stefan
 */
public class MeetingReport extends javax.swing.JFrame {

    private AssignedMeetingsController parentController;
    
    public MeetingReport() {
        initComponents();
    }
    
    public MeetingReport(AssignedMeetingsController controller, Meeting meeting, Report report, String clientName, String employeeName) {
        initComponents();
        
        parentController = controller;
        
        buttonExit.addActionListener(parentController);
        
        fillForm(meeting, report, clientName, employeeName);
    }
    
    private void fillForm(Meeting meeting, Report report, String clientName, String employeeName) {
        SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
        
        inputClient.setText(clientName);
        inputEmployee.setText(employeeName);
        inputDate.setText(dateFormatter.format(meeting.getMeetingDate()));
        inputDescription.setText(meeting.getDescription());
        inputFeedback.setText(String.valueOf(meeting.getFeedback()));
        checkBoxFinished.setSelected(!meeting.getIsOpen());
        inputReport.setText(report.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelClient = new javax.swing.JLabel();
        labelEmployee = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        labelFeedback = new javax.swing.JLabel();
        labelFinished = new javax.swing.JLabel();
        checkBoxFinished = new javax.swing.JCheckBox();
        inputClient = new javax.swing.JTextField();
        inputEmployee = new javax.swing.JTextField();
        inputDate = new javax.swing.JTextField();
        inputDescription = new javax.swing.JTextField();
        inputFeedback = new javax.swing.JTextField();
        labelReport = new javax.swing.JLabel();
        inputReport = new javax.swing.JTextField();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTitle.setText("Meeting Report");

        labelClient.setText("Client");

        labelEmployee.setText("Employee");

        labelDate.setText("Date");

        labelDescription.setText("Description");

        labelFeedback.setText("Feedback");

        labelFinished.setText("Finished");

        checkBoxFinished.setEnabled(false);

        inputClient.setEditable(false);
        inputClient.setToolTipText("");

        inputEmployee.setEditable(false);

        inputDate.setEditable(false);

        inputDescription.setEditable(false);

        inputFeedback.setEditable(false);

        labelReport.setText("Report");
        labelReport.setToolTipText("");

        inputReport.setEditable(false);

        buttonExit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmployee)
                    .addComponent(labelClient)
                    .addComponent(labelDate)
                    .addComponent(labelDescription)
                    .addComponent(labelFeedback)
                    .addComponent(labelFinished)
                    .addComponent(labelReport))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonExit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputReport, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(checkBoxFinished)
                                .addComponent(labelTitle)
                                .addComponent(inputClient)
                                .addComponent(inputEmployee)
                                .addComponent(inputDate, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addComponent(inputDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addComponent(inputFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                        .addContainerGap(186, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTitle)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClient)
                    .addComponent(inputClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmployee)
                    .addComponent(inputEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDate)
                    .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescription)
                    .addComponent(inputDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFeedback)
                    .addComponent(inputFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFinished)
                    .addComponent(checkBoxFinished))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelReport)
                    .addComponent(inputReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(buttonExit)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeetingReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeetingReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeetingReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeetingReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeetingReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JCheckBox checkBoxFinished;
    private javax.swing.JTextField inputClient;
    private javax.swing.JTextField inputDate;
    private javax.swing.JTextField inputDescription;
    private javax.swing.JTextField inputEmployee;
    private javax.swing.JTextField inputFeedback;
    private javax.swing.JTextField inputReport;
    private javax.swing.JLabel labelClient;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelEmployee;
    private javax.swing.JLabel labelFeedback;
    private javax.swing.JLabel labelFinished;
    private javax.swing.JLabel labelReport;
    private javax.swing.JLabel labelTitle;
    // End of variables declaration//GEN-END:variables
}
